const ADD_MESSAGE = 'ADD_MESSAGE'
const UPDATE_CURRENT_MESSAGE = 'UPDATE_CURRENT_MESSAGE'

const ADD_POST = 'ADD_POST'
const UPDATE_CURRENT_POST_MESSAGE = 'UPDATE_CURRENT_POST_MESSAGE'

export default { ADD_MESSAGE, UPDATE_CURRENT_MESSAGE, ADD_POST, UPDATE_CURRENT_POST_MESSAGE }